// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa-ahI5Eos6L-MPDgyXugev2g0Acs10a8',
    appId: '1:215244382111:web:40c883d42a7a8f5aa8e7aa',
    messagingSenderId: '215244382111',
    projectId: 'avesdesanmartin-54ccc',
    authDomain: 'avesdesanmartin-54ccc.firebaseapp.com',
    storageBucket: 'avesdesanmartin-54ccc.appspot.com',
    measurementId: 'G-E3E7W3QPTX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOgJvkbmZX3SpMEEJasTMZrHp5PymLR_8',
    appId: '1:215244382111:android:9087ddac025f2ddca8e7aa',
    messagingSenderId: '215244382111',
    projectId: 'avesdesanmartin-54ccc',
    storageBucket: 'avesdesanmartin-54ccc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8kQOQJeZDwt8yUbzdhI4fwT64sUOUKmk',
    appId: '1:215244382111:ios:2767902c3070a017a8e7aa',
    messagingSenderId: '215244382111',
    projectId: 'avesdesanmartin-54ccc',
    storageBucket: 'avesdesanmartin-54ccc.appspot.com',
    androidClientId: '215244382111-sigeogjncjr8hqvt95civjdvrtvm5rrf.apps.googleusercontent.com',
    iosClientId: '215244382111-vdek0od74drifd4t59t53l2jlud66mnt.apps.googleusercontent.com',
    iosBundleId: 'com.example.avesDeSanMartin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8kQOQJeZDwt8yUbzdhI4fwT64sUOUKmk',
    appId: '1:215244382111:ios:2767902c3070a017a8e7aa',
    messagingSenderId: '215244382111',
    projectId: 'avesdesanmartin-54ccc',
    storageBucket: 'avesdesanmartin-54ccc.appspot.com',
    androidClientId: '215244382111-sigeogjncjr8hqvt95civjdvrtvm5rrf.apps.googleusercontent.com',
    iosClientId: '215244382111-vdek0od74drifd4t59t53l2jlud66mnt.apps.googleusercontent.com',
    iosBundleId: 'com.example.avesDeSanMartin',
  );
}
